NRI課題
ryoma-yama/ryoma-yamanouchi pull request #1
Opened 2020-04-07 13:45 UTC by ryoma-yama

## やったこと
- マークアップ
## やっていないこと
- ハンバーガーメニューの実装

2020-04-09 03:12 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-09 03:12 UTC, piasoratech commented on html-nri/index.html
> +            <span class="title-sub">NRIのデジタルビジネス戦略</span></h1>
`h1`タグは題名を表すようなイメージを持つので、サブタイトルのような要素は含まないです。

2020-04-09 03:12 UTC, piasoratech commented on html-nri/index.html
> +                <p><a href="#">人材が支えるNRI</a>&gt;</p>
`<`や`>`は疑似要素を使って実現しましょう

2020-04-09 03:12 UTC, piasoratech commented on html-nri/index.html
> +            <div class="page-back">
`div`で囲った意図はなんでしょうか？

2020-04-09 03:12 UTC, piasoratech commented on html-nri/index.html
> +            <h2>Follow Us</h2>
ここは見出しではないですね

2020-04-09 03:12 UTC, piasoratech commented on html-nri/index.html
> +        <ol class="breadcrumb">
`breadcrumb`はパンくずを表す単語なので、パンくずリストの場合は複数形にするのが正しいです。

2020-04-09 05:04 UTC, ryoma-yama commented on html-nri/index.html
> +            <div class="page-back">
階層を揃えるために囲いました。
かえって複雑になっているので、外しました。

2020-04-09 08:32 UTC, ryoma-yama commented
該当箇所とtypoの修正、footerのタグ調整を行いました。

2020-04-09 15:31 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
あと少し！

2020-04-09 15:31 UTC, piasoratech commented on html-nri/index.html
> +                    <img src="images/nri-logo.png" alt="nri-logo"></a></li>
この辺り変に階層分かれてるのが気になりますね。
改行せずに書いてしまってもいいかもしれません。(他の部分も)

2020-04-09 15:31 UTC, piasoratech commented on html-nri/index.html
> +                <h1>NRIのデジタルビジネス戦略</h1>
文章構造を考えると逆かと

2020-04-10 00:19 UTC, ryoma-yama commented
imgタグ前の改行の削除と、h1部分のタグを入れ替えました。

2020-04-10 03:09 UTC, piasoratech approved these changes
良いかと！

2020-04-10 03:53 UTC, Yuzunoha approved these changes
LGTMです！！！

2020-04-10 05:09 UTC, ryoma-yama commented
footerに抜けていたコンテンツを追加しました。

2020-04-10 07:00 UTC, ryoma-yama commented
- 2060301 にて、footerに抜けていたコンテンツの追加をしました。
- 3c6b8a4 にて、上記のコンテンツへリンクを付け足して、同リスト内に使っていた`h2`を削除しました。文章構造的に見出しは適当ではないと判断したためです。

2020-04-10 07:16 UTC, piasoratech approved these changes
良いかと！

2020-04-14 06:54 UTC, ryoma-yama commented
- d746231 にて、画像としてハンバーガーメニューとpsdのアイコンを追加しました。HTMLはそれに合わせての追記と一箇所リンク抜けがあったので修正しています。そして、CSSのコーディングが完了したので提出します。

2020-04-14 07:02 UTC, piasoratech requested changes
・ヘッダーのNRIロゴがもう少し内側、文字とアイコンとの間をもう少しあけるようにしましょう。
(提出していただいたもの)
![image](https://user-images.githubusercontent.com/57445698/79195467-499e5300-7e69-11ea-9adb-aae78b18edaa.png)

(見本)
![image](https://user-images.githubusercontent.com/57445698/79195477-502cca80-7e69-11ea-9847-6be2b51b21c4.png)

2020-04-14 07:32 UTC, ryoma-yama commented
- 669c41e にて、ご指摘のあった箇所の各余白を調整しました。

2020-04-14 07:35 UTC, piasoratech approved these changes
良いかと！

2020-04-14 14:07 UTC, merged