家具屋サイトの作成
ryoma-yama/ryoma-yamanouchi pull request #2
Opened 2020-04-16 02:56 UTC by ryoma-yama

画像などのアセットとHomeのHTMLをコミットしました。

2020-04-16 03:05 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +            <img class="header-nav__img" src="images/logo_header.png" srcset="images/logo_header.png 1x, images/logo_header@2x.png 2x" alt="">
`alt`に適切な文言を入れましょう

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +                <span class="h1-home__third">a life.</span>
`xxxxfirst`もマジックナンバーを使ってるのと変わらないので使うのやめましょう
あと変数名の中に`-`と`_`は混在させずどちらかに統一しましょう。

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +            <h1 class="h1-home">
この要素は`header`ではないですね。

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +                        <figcaption class="main-contents__unordered-list--second">アームストロングのチェア入荷</figcaption>
見本と文言が違うので確認しましょう

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +                <Li>
htmlタグは通常小文字で記載します。

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +            </form>
インデントをそろえましょう

2020-04-16 03:05 UTC, piasoratech commented on html-kaguya/index.html
> +        <p class="footer-copyright">&copy;HTMLCSS.code</p>
コピーライト部分に適切なタグがあるので調べて使用しましょう

2020-04-16 05:30 UTC, ryoma-yama commented on html-kaguya/index.html
> +                <span class="h1-home__third">a life.</span>
擬似クラスでスタイルを適用することにしたのでマジックナンバーとなっていたクラスは削除しました。
変数名についてですが、カリキュラムに乗っていたBEMを試してみたくてアンダースコアも使っています。この場合でも記号を統一するなどして書いた方が良いのでしょうか。

2020-04-16 05:35 UTC, ryoma-yama commented on html-kaguya/index.html
> +            <h1 class="h1-home">
`main`に移動しました。

2020-04-16 05:57 UTC, ryoma-yama commented on html-kaguya/index.html
> +                <span class="h1-home__third">a life.</span>
> `xxxxfirst`もマジックナンバーを使ってるのと変わらないので使うのやめましょう

擬似クラスでスタイルを適用することにしたのでマジックナンバーとなっていたクラスは削除しました。

> あと変数名の中に`-`と`_`は混在させずどちらかに統一しましょう。

変数名についてですが、カリキュラムに乗っていたBEMを試してみたくてアンダースコアも使っています。失礼とは存じますが、この場合でも記号を統一して書いた方が良いのでしょうか。

2020-04-16 06:12 UTC, ryoma-yama commented on html-kaguya/index.html
> +            </form>
`p`タグで囲うかたちでインデントを揃えました。親要素の`form`と横幅をあわせる目的もあります。

2020-04-16 07:13 UTC, ryoma-yama commented
0ee245c にて、ご指摘頂いた箇所に対応しました。あと`head`の文言が変だったので書き直しました。それと`main`のclassを付け直しました。

2020-04-16 08:26 UTC, piasoratech approved these changes
良いかと
次に進みましょう！

2020-04-17 01:25 UTC, ryoma-yama commented
2d0b1c7 にてHome以外のHTMLを追加しました。他に、スマホ用のアセット追加、すべてのページの整形を行いました。

2020-04-17 01:36 UTC, ryoma-yama commented
2d0b1c7 にてHome以外のHTMLを追加しました。他に、スマホ用のアセット追加、すべてのページの整形を行いました。
8a3453 にてrecruitページのみタブがスペース2つでなかったため再度整形しました。

2020-04-17 01:36 UTC, ryoma-yama commented
2d0b1c7 にてHome以外のHTMLを追加しました。他に、スマホ用のアセット追加、すべてのページの整形を行いました。
8a3453e にてrecruitページのみタブがスペース2つでなかったため再度整形しました。

2020-04-17 03:03 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-17 03:03 UTC, piasoratech commented on html-kaguya/recruit.html
> +                  <li>週３〜5日</li>
３は半角です

2020-04-17 03:03 UTC, piasoratech commented on html-kaguya/recruit.html
> +                  <li>週３〜5日</li>
3は半角です

2020-04-17 04:02 UTC, ryoma-yama commented
5a25620 にてご指摘頂いた箇所の3を全角から半角にしました。

2020-04-17 04:12 UTC, choimake commented
修正ありがとうございました。
LGTMです。

2020-04-17 11:05 UTC, merged