家具屋CSS
ryoma-yama/ryoma-yamanouchi pull request #3
Opened 2020-04-20 08:15 UTC by ryoma-yama

HOMEのCSSができたので提出します。

2020-04-20 08:31 UTC, piasoratech requested changes
・全体的にXDで設定されている値と異なる部分が多いので確認をしてください。

2020-04-20 09:22 UTC, ryoma-yama commented
f43f337 にて、margin等の余白や文字色などを全体的に修正しました。

2020-04-21 06:17 UTC, ryoma-yama commented
f43f337 にて、margin等の余白や文字色などを全体的に修正しました。
485c415 にて、font関係で不足していた値の追加をしました。

2020-04-21 06:48 UTC, choimake commented
こちらでみたところ、デザインがかなり崩れていました。
確認お願いします。

<img width="1439" alt="スクリーンショット 2020-04-21 15 44 48" src="https://user-images.githubusercontent.com/52233450/79834123-78777480-83e7-11ea-9b7f-30566bc76357.png">

2020-04-21 07:05 UTC, choimake commented
確認取れました。LGTMです。

2020-04-21 13:27 UTC, ryoma-yama commented
79e1e23 にて、recruitトップ画像追加、各ページのクラス名を付け直しました。各ページのCSSを記述したので提出します。

2020-04-22 02:47 UTC, choimake commented
home、contactの問い合わせ内容にフォーカスを当てたときの文字の入力位置が「問い合わせ内容」のplaceholderの上に書かれている点にデザイン的にな違和感を感じます。
文字の入力位置を「問い合わせ内容」の上にフォーカスがくるように修正をお願いします。

<img width="546" alt="スクリーンショット 2020-04-22 11 33 56" src="https://user-images.githubusercontent.com/52233450/79934344-4a4c7000-848d-11ea-87ac-1a612973f6b4.png">

2020-04-22 02:59 UTC, ryoma-yama commented
e2f4edf にて、line-heightとpaddingを調整する形で、textareaでの入力位置を修正しました。

2020-04-22 03:45 UTC, choimake commented
修正ありがとうございました。LGTMです。

2020-04-23 02:05 UTC, ryoma-yama commented
e16cba0 にて、家具屋Homeのレスポンシブ対応をしました。
- HTMLではコンテンツを一つ追加しています。Contactの"Send"ボタンです。

2020-04-23 03:27 UTC, choimake reviewed
コメントしましたので確認お願いします。

2020-04-23 03:27 UTC, choimake commented on html-kaguya/style.css
> +@media (max-width: 350px) {
スマホ時のブレイクポイントは以下リンクにあるように375pxです。
https://quelcode.slite.com/app/channels/LnKDoZ3TlY/notes/UPkjyk~nGH#b04dab40

こちら仕様に合わせて修正お願いします。
他にも該当箇所がありますので、そちらも合わせて修正してください。

2020-04-23 04:29 UTC, ryoma-yama commented
3da43c8 にて、スマホ時のブレイクポイントを375pxに修正しました。

2020-04-23 05:18 UTC, choimake commented
下にスクロールした時に、headerが1/3ほどめりこむ挙動が見受けられますので、こちらめりこみがなくなるように修正お願いします。

<img width="274" alt="スクリーンショット 2020-04-23 14 13 42" src="https://user-images.githubusercontent.com/52233450/80061645-d8e3ee80-856c-11ea-8566-9786ce4e374b.png">

2020-04-23 05:45 UTC, ryoma-yama commented
10eac09 にて、header部分に絶対値の高さを指定しました。
めり込む挙動ですが、こちらからブラウザのGoogleChrome, FireFox, Safariを使って見たところ、確認できなかったため、挙動が修正されたかどうかを確認できておりません。
すみませんが、確認よろしくお願いいたします。

2020-04-23 05:49 UTC, choimake commented
対応ありがとうございました。LGTMです。

2020-04-23 08:47 UTC, ryoma-yama commented
1b1ae9e にて、Home以外のレスポンシブ対応をしました。
- HTMLには足りなかったコンテンツを追加しています。

2020-04-23 09:10 UTC, choimake commented
リストで表示しているところの点がXDのデータに比べてかなり大きいです。
前回の指摘漏れに当たる部分で申し訳ありませんが修正お願いします。

<img width="786" alt="スクリーンショット 2020-04-23 18 09 14" src="https://user-images.githubusercontent.com/52233450/80081208-98e13380-858d-11ea-8400-98480ae48069.png">

2020-04-23 09:52 UTC, ryoma-yama commented
c45f5bc にて、リスト記号を擬似要素で置き換えて小さめにしました。

また、フォント指定をNoto Sansに修正しました。
Noto Sans JPを日本語版だと思って使っていたためです。

それと、スマートフォン版のNewsページの画像の不透明度ですが、60%としています。
見た目では40%ぐらいに見える所ですが、アピアランスでは60%となっているためです。

2020-04-24 02:34 UTC, choimake commented
対応ありがとうございました。LGTMです！

2020-04-24 14:27 UTC, merged